services:
  linuxserver:
    image: lscr.io/linuxserver/code-server:latest
    restart: unless-stopped
    ports:
      - "3020:8443"
    volumes:
      - ./.docker/config:/config
      - ./.docker/workspace:/config/workspace
    environment:
      TZ: Europe/Prague
