services:
  theia:
    image: ghcr.io/eclipse-theia/theia-ide/theia-ide:latest
    restart: unless-stopped
    ports:
      - "3040:3000"
    volumes:
      - ./.docker/workspace:/home/project
    user: root
